services:
  db:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: kskphotos
      POSTGRES_PASSWORD: kskphotos_dev
      POSTGRES_DB: photo_portfolio
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
